use_frameworks!

platform :ios, '8.0'

target 'YwfUtil_Example' do
  pod 'YwfUtil', :path => '../'

  target 'YwfUtil_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
